package com.category;

import java.util.HashMap;
import java.util.Map;

import org.apache.hadoop.hive.ql.exec.UDF;
import org.apache.hadoop.io.Text;

import uk.ac.shef.wit.simmetrics.similaritymetrics.AbstractStringMetric;
import uk.ac.shef.wit.simmetrics.similaritymetrics.Levenshtein;
import uk.ac.shef.wit.simmetrics.similaritymetrics.MongeElkan;

public class GetCategory  extends UDF{

	static String text = "";
	 static Map<String, String> dictionary = new HashMap<String, String>();
    private static void initDictionary() {

        dictionary.put("Internet","Network / Data");
        dictionary.put("خط","Network / Other Network");
        dictionary.put("wired","Network / Data");
        dictionary.put("data","Network / Data");
        dictionary.put("broadband","Network / Data");
        dictionary.put("router","Network / Data");
        dictionary.put("switch router","Network / Data");
        dictionary.put("offline","Network / Data");
        dictionary.put("download","Network / Data");
        dictionary.put("Upload","Network / Data");
        dictionary.put("speed","Network / Data");
        dictionary.put("4G","Network / Data");
        dictionary.put("3G","Network / Data");
        dictionary.put("LTE","Network / Data");
        dictionary.put("connection","Network / Data");
        dictionary.put("disconnection","Network / Data");
        dictionary.put("signal","Network / Data");
        dictionary.put("GPRS","Network / Data");
        dictionary.put("EDGE","Network / Data");
        dictionary.put("WIFI","Network / Data");
        dictionary.put("megabytes","Network / Data");
        dictionary.put("Mega Bytes","Network / Data");
        dictionary.put("MB","Network / Data");
        dictionary.put("gigabyte","Network / Data");
        dictionary.put("Giga Byte","Network / Data");
        dictionary.put("GB","Network / Data");
        dictionary.put("Network","Network / Voice");
        dictionary.put("call","Network / Voice");
        dictionary.put("voice","Network / Voice");
        dictionary.put("drop call","Network / Voice");
        dictionary.put("breaking","Network / Voice");
        dictionary.put("Coverage","Network / Other Network");
        dictionary.put("system down","Network / Other Network");
        dictionary.put("service","Network / Other Network");
        dictionary.put("voicemail","Network / Other Network");
        dictionary.put("voice mail","Network / Other Network");
        dictionary.put("sms","Network / Other Network");
        dictionary.put("text","Network / Other Network");
        dictionary.put("signal","Network / Other Network");
        dictionary.put("signal problem","Network / Other Network");
        dictionary.put("RBT","Network / Other Network");
        dictionary.put("Ring Back Tone","Network / Other Network");
        dictionary.put("chat","Network / Other Network");
        dictionary.put("Customer","Customer Care / Customer Care");
        dictionary.put("Waiting time","Customer Care / Customer Care");
        dictionary.put("queue","Customer Care / Customer Care");
        dictionary.put("Time","Customer Care / Customer Care");
        dictionary.put("Wait","Customer Care / Customer Care");
        dictionary.put("customer","Customer Care / Customer Care");
        dictionary.put("help","Customer Care / Customer Care");
        dictionary.put("assistance","Customer Care / Customer Care");
        dictionary.put("waste of time","Customer Care / Customer Care");
        dictionary.put("unresolved","Customer Care / Customer Care");
        dictionary.put("not working","Customer Care / Customer Care");
        dictionary.put("not operational","Customer Care / Customer Care");
        dictionary.put("resolve","Customer Care / Customer Care");
        dictionary.put("issue","Customer Care / Customer Care");
        dictionary.put("subscriber","Customer Care / Customer Care");
        dictionary.put("contract","Customer Care / Customer Care");
        dictionary.put("friendly","Customer Care / Customer Care");
        dictionary.put("rude","Customer Care / Customer Care");
        dictionary.put("complaint","Customer Care / Customer Care");
        dictionary.put("Phone","Business Affairs / Handset");
        dictionary.put("Mobile","Business Affairs / Handset");
        dictionary.put("iphone","Business Affairs / Handset");
        dictionary.put("HTC","Business Affairs / Handset");
        dictionary.put("LG","Business Affairs / Handset");
        dictionary.put("IOS","Business Affairs / Handset");
        dictionary.put("Android","Business Affairs / Handset");
        dictionary.put("handset","Business Affairs / Handset");
        dictionary.put("samsung","Business Affairs / Handset");
        dictionary.put("sony","Business Affairs / Handset");
        dictionary.put("shop","Business Affairs / Shops");
        dictionary.put("mall","Business Affairs / Shops");
        dictionary.put("ticket number","Business Affairs / Shops");
        dictionary.put("bill","Business Affairs / Pricing or Billing");
        dictionary.put("charge","Business Affairs / Pricing or Billing");
        dictionary.put("pay","Business Affairs / Pricing or Billing");
        dictionary.put("money","Business Affairs / Pricing or Billing");
        dictionary.put("refund","Business Affairs / Pricing or Billing");
        dictionary.put("credit","Business Affairs / Pricing or Billing");
        dictionary.put("النت","Network / Data");
        dictionary.put("لينك","Network / Data");
        dictionary.put("USB","Network / Data");
        dictionary.put("داتا","Network / Data");
        dictionary.put("الانترنت","Network / Data");
        dictionary.put("الداون لود","Network / Data");
        dictionary.put("ميجا","Network / Data");
        dictionary.put("الدونلود","Network / Data");
        dictionary.put("ADSL","Network / Data");
        dictionary.put("h+","Network / Data");
        dictionary.put("e","Network / Data");
        dictionary.put("جيجا","Network / Data");
        dictionary.put("الدي اس ال","Network / Data");
        dictionary.put("تحميل","Network / Data");
        dictionary.put("سرعة","Network / Data");
        dictionary.put("بتفصل","Network / Data");
        dictionary.put("موبيل انترنت","Network / Data");
        dictionary.put("انترنت","Network / Data");
        dictionary.put("نت","Network / Data");
        dictionary.put("الفلاشة","Network / Data");
        dictionary.put("فلاشة","Network / Data");
        dictionary.put("الواتس اب","Network / Data");
        dictionary.put("الجيجابايتس","Network / Data");
        dictionary.put("واي فاي","Network / Data");
        dictionary.put("WCDMA","Network / Data");
        dictionary.put("بياناتي","Network / Data");
        dictionary.put("ڤيروس","Network / Data");
        dictionary.put("جيحا","Network / Data");
        dictionary.put("ويفاي","Network / Data");
        dictionary.put("موزيلا","Network / Data");
        dictionary.put("جيجابايتس","Network / Data");
        dictionary.put("وايفاي","Network / Data");
        dictionary.put("الميجات","Network / Data");
        dictionary.put("الميجا","Network / Data");
        dictionary.put("التحميل","Network / Data");
        dictionary.put("الايميل","Network / Data");
        dictionary.put("ميديا","Network / Data");
        dictionary.put("ميجات","Network / Data");
        dictionary.put("ميجابيت","Network / Data");
        dictionary.put("ميجابتس","Network / Data");
        dictionary.put("ميجابايتس","Network / Data");
        dictionary.put("ميجابايت","Network / Data");
        dictionary.put("موديم","Network / Data");
        dictionary.put("مودم","Network / Data");
        dictionary.put("لينكات","Network / Data");
        dictionary.put("للينك","Network / Data");
        dictionary.put("للنت","Network / Data");
        dictionary.put("للراوتر","Network / Data");
        dictionary.put("للانترنت","Network / Data");
        dictionary.put("لروتر","Network / Data");
        dictionary.put("لانترنت","Network / Data");
        dictionary.put("فلاش","Network / Data");
        dictionary.put("فراوتر","Network / Data");
        dictionary.put("فايرفوكس","Network / Data");
        dictionary.put("أوبرا","Network / Data");
        dictionary.put("الكروم","Network / Data");
        dictionary.put("الفايرفوكس","Network / Data");
        dictionary.put("فالانترنت","Network / Data");
        dictionary.put("غيغابايتس","Network / Data");
        dictionary.put("روتر","Network / Data");
        dictionary.put("الوايرلس","Network / Data");
        dictionary.put("داونلود","Network / Data");
        dictionary.put("حمل","Network / Data");
        dictionary.put("جييييجا","Network / Data");
        dictionary.put("بورتال","Network / Data");
        dictionary.put("بميجا","Network / Data");
        dictionary.put("بالراوتر","Network / Data");
        dictionary.put("الميجابيت","Network / Data");
        dictionary.put("الميجابايتس","Network / Data");
        dictionary.put("الميجابايت","Network / Data");
        dictionary.put("المودم","Network / Data");
        dictionary.put("الروتر","Network / Data");
        dictionary.put("الراوتور","Network / Data");
        dictionary.put("الراوتر","Network / Data");
        dictionary.put("الداونلوود","Network / Data");
        dictionary.put("الداونلود","Network / Data");
        dictionary.put("الداتا","Network / Data");
        dictionary.put("الجيجات","Network / Data");
        dictionary.put("الجيجابايت","Network / Data");
        dictionary.put("الجيجا","Network / Data");
        dictionary.put("الانترنيت","Network / Data");
        dictionary.put("vpn","Network / Data");
        dictionary.put("modem","Network / Data");
        dictionary.put("mifi","Network / Data");
        dictionary.put("mi-fi","Network / Data");
        dictionary.put("hotspot","Network / Data");
        dictionary.put("dsl","Network / Data");
        dictionary.put("browsing","Network / Data");
        dictionary.put("browser","Network / Data");
        dictionary.put("Hub","Network / Data");
        dictionary.put("الاتصال","Network / Voice");
        dictionary.put("اتصل","Network / Voice");
        dictionary.put("المكالمه","Network / Voice");
        dictionary.put("لشبكة واقعة","Network / Voice");
        dictionary.put("مكالمه","Network / Voice");
        dictionary.put("بيتصل","Network / Voice");
        dictionary.put("بيستقبل","Network / Voice");
        dictionary.put("مكالمات","Network / Voice");
        dictionary.put("بتستقبل","Network / Voice");
        dictionary.put("بتتصل","Network / Voice");
        dictionary.put("غير متاح","Network / Voice");
        dictionary.put("رن","Network / Voice");
        dictionary.put("مكالمة","Network / Voice");
        dictionary.put("فصل","Network / Voice");
        dictionary.put("بتصل","Network / Voice");
        dictionary.put("مكامله","Network / Voice");
        dictionary.put("مكالمى","Network / Voice");
        dictionary.put("اتكلمت","Network / Voice");
        dictionary.put("مكالمتين","Network / Voice");
        dictionary.put("مكالمتكم","Network / Voice");
        dictionary.put("مكالمتك","Network / Voice");
        dictionary.put("مكالماتكم","Network / Voice");
        dictionary.put("mokalmat","Network / Voice");
        dictionary.put("يرن","Network / Voice");
        dictionary.put("التغطية","Network / Coverage");
        dictionary.put("ابراج ارسال","Network / Coverage");
        dictionary.put("السيجنال","Network / Coverage");
        dictionary.put("جهاز التوجيه","Network / Coverage");
        dictionary.put("إشارة","Network / Coverage");
        dictionary.put("الشبكه بتطلع وتنزل","Network / Coverage");
        dictionary.put("signal","Network / Coverage");
        dictionary.put("السجنال","Network / Coverage");
        dictionary.put("التغطيه","Network / Coverage");
        dictionary.put("الشبكات","Network / Coverage");
        dictionary.put("الشبكه","Network / Coverage");
        dictionary.put("الشبكة ","Network / Coverage");
        dictionary.put("للتغطية","Network / Coverage");
        dictionary.put("الشبكة","Network / Coverage");
        dictionary.put("تغطية","Network / Coverage");
        dictionary.put("للشبكه","Network / Coverage");
        dictionary.put("للشبكة","Network / Coverage");
        dictionary.put("للشبكات","Network / Coverage");
        dictionary.put("لشبكه","Network / Coverage");
        dictionary.put("لشبكتكم","Network / Coverage");
        dictionary.put("لشبكة","Network / Coverage");
        dictionary.put("فالشبكة","Network / Coverage");
        dictionary.put("شبكه","Network / Coverage");
        dictionary.put("شبكة","Network / Coverage");
        dictionary.put("شبكات","Network / Coverage");
        dictionary.put("التجوال","Network / Roaming");
        dictionary.put("تجوال","Network / Roaming");
        dictionary.put("roaming","Network / Roaming");
        dictionary.put("مسج","Network / Messaging");
        dictionary.put("المسجات","Network / Messaging");
        dictionary.put("الرسايل","Network / Messaging");
        dictionary.put("الرسالة","Network / Messaging");
        dictionary.put("رساله","Network / Messaging");
        dictionary.put("رسالتين","Network / Messaging");
        dictionary.put("رسالة","Network / Messaging");
        dictionary.put("رساايل","Network / Messaging");
        dictionary.put("رسائيل","Network / Messaging");
        dictionary.put("رسائل","Network / Messaging");
        dictionary.put("مسدجاتكم","Network / Messaging");
        dictionary.put("مسدجات","Network / Messaging");
        dictionary.put("مسدج","Network / Messaging");
        dictionary.put("مسجات","Network / Messaging");
        dictionary.put("شريحة","Network / Other Network");
        dictionary.put("خطي","Network / Other Network");
        dictionary.put("الشريحة","Network / Other Network");
        dictionary.put("الشرايح","Network / Other Network");
        dictionary.put("الخط","Network / Other Network");
        dictionary.put("التغطيه","Network / Other Network");
        dictionary.put("نمرة","Network / Other Network");
        dictionary.put("النمرة","Network / Other Network");
        dictionary.put("الكارير","Network / Other Network");
        dictionary.put("puk","Network / Other Network");
        dictionary.put("imei","Network / Other Network");
        dictionary.put("خدمه العملاء","Customer Care / Customer Care");
        dictionary.put("خدمة العملا","Customer Care / Customer Care");
        dictionary.put("كول سنتر","Customer Care / Customer Care");
        dictionary.put("تواصلت","Customer Care / Customer Care");
        dictionary.put("كنترول","Customer Care / Customer Care");
        dictionary.put("موظف","Customer Care / Customer Care");
        dictionary.put("الكوستمر سيرفيس","Customer Care / Customer Care");
        dictionary.put("الكستمر سيرفيس","Customer Care / Customer Care");
        dictionary.put("الادمن","Customer Care / Customer Care");
        dictionary.put("ادمين","Customer Care / Customer Care");
        dictionary.put("ادمن","Customer Care / Customer Care");
        dictionary.put("call center","Customer Care / Customer Care");
        dictionary.put("CS","Customer Care / Customer Care");
        dictionary.put("customer support","Customer Care / Customer Care");
        dictionary.put("الكول سنتر","Customer Care / Customer Care");
        dictionary.put("الفون","Business Affairs / Handset");
        dictionary.put("الجوال","Business Affairs / Handset");
        dictionary.put("الموبايل","Business Affairs / Handset");
        dictionary.put("موبيله","Business Affairs / Handset");
        dictionary.put("الأيفون","Business Affairs / Handset");
        dictionary.put("سامسونج","Business Affairs / Handset");
        dictionary.put("سوني","Business Affairs / Handset");
        dictionary.put("xperia","Business Affairs / Handset");
        dictionary.put("لوميا ","Business Affairs / Handset");
        dictionary.put("تليفوني","Business Affairs / Handset");
        dictionary.put("آبل","Business Affairs / Handset");
        dictionary.put("فون","Business Affairs / Handset");
        dictionary.put("نوكيا","Business Affairs / Handset");
        dictionary.put("هواوي","Business Affairs / Handset");
        dictionary.put("موبيل","Business Affairs / Handset");
        dictionary.put("موبايل","Business Affairs / Handset");
        dictionary.put("لينوفو","Business Affairs / Handset");
        dictionary.put("لوميا","Business Affairs / Handset");
        dictionary.put("للفون","Business Affairs / Handset");
        dictionary.put("للبلاكبيري","Business Affairs / Handset");
        dictionary.put("للايباد","Business Affairs / Handset");
        dictionary.put("ايباد","Business Affairs / Handset");
        dictionary.put("لبلاكبيري","Business Affairs / Handset");
        dictionary.put("سمسونج","Business Affairs / Handset");
        dictionary.put("جلاكسى","Business Affairs / Handset");
        dictionary.put("جالكسى","Business Affairs / Handset");
        dictionary.put("جالاكسى","Business Affairs / Handset");
        dictionary.put("ايفون","Business Affairs / Handset");
        dictionary.put("ايدج","Business Affairs / Handset");
        dictionary.put("اندرويد","Business Affairs / Handset");
        dictionary.put("التابلت","Business Affairs / Handset");
        dictionary.put("التاب","Business Affairs / Handset");
        dictionary.put("البلاكبيري","Business Affairs / Handset");
        dictionary.put("الايباد","Business Affairs / Handset");
        dictionary.put("s6","Business Affairs / Handset");
        dictionary.put("s4","Business Affairs / Handset");
        dictionary.put("s2","Business Affairs / Handset");
        dictionary.put("nokia","Business Affairs / Handset");
        dictionary.put("lgg3","Business Affairs / Handset");
        dictionary.put("galaxy","Business Affairs / Handset");
        dictionary.put("g3","Business Affairs / Handset");
        dictionary.put("s5","Business Affairs / Handset");
        dictionary.put("NEXUS","Business Affairs / Handset");
        dictionary.put("Huawei","Business Affairs / Handset");
        dictionary.put("Apple","Business Affairs / Handset");
        dictionary.put("الفرع","Business Affairs / Shops");
        dictionary.put("فرع","Business Affairs / Shops");
        dictionary.put("كونتر","Business Affairs / Shops");
        dictionary.put("فروع","Business Affairs / Shops");
        dictionary.put("الستورز","Business Affairs / Shops");
        dictionary.put("center","Business Affairs / Shops");
        dictionary.put("الرصيد","Business Affairs / Pricing or Billing");
        dictionary.put("اشحن","Business Affairs / Pricing or Billing");
        dictionary.put("فلوس","Business Affairs / Pricing or Billing");
        dictionary.put("رصيدي","Business Affairs / Pricing or Billing");
        dictionary.put("تحويل الرصيد","Business Affairs / Pricing or Billing");
        dictionary.put("فتوره","Business Affairs / Pricing or Billing");
        dictionary.put("بتشحن","Business Affairs / Pricing or Billing");
        dictionary.put("رصيد","Business Affairs / Pricing or Billing");
        dictionary.put("نصب","Business Affairs / Pricing or Billing");
        dictionary.put("السرقة","Business Affairs / Pricing or Billing");
        dictionary.put("شاحن","Business Affairs / Pricing or Billing");
        dictionary.put("بتكلفنى","Business Affairs / Pricing or Billing");
        dictionary.put("الفلوس","Business Affairs / Pricing or Billing");
        dictionary.put("بيحسبه","Business Affairs / Pricing or Billing");
        dictionary.put("نصبين","Business Affairs / Pricing or Billing");
        dictionary.put("حرمية","Business Affairs / Pricing or Billing");
        dictionary.put("الفاتورة","Business Affairs / Pricing or Billing");
        dictionary.put("adfa3","Business Affairs / Pricing or Billing");
        dictionary.put("حسابي","Business Affairs / Pricing or Billing");
        dictionary.put("جنيه","Business Affairs / Pricing or Billing");
        dictionary.put("قرش","Business Affairs / Pricing or Billing");
        dictionary.put("ينصب","Business Affairs / Pricing or Billing");
        dictionary.put("يشحن","Business Affairs / Pricing or Billing");
        dictionary.put("يتنصب","Business Affairs / Pricing or Billing");
        dictionary.put("نصابين","Business Affairs / Pricing or Billing");
        dictionary.put("حرامية","Business Affairs / Pricing or Billing");
        dictionary.put("يسرق","Business Affairs / Pricing or Billing");
        dictionary.put("دفعت","Business Affairs / Pricing or Billing");
        dictionary.put("حراميه","Business Affairs / Pricing or Billing");
        dictionary.put("وحدات","Business Affairs / Pricing or Billing");
        dictionary.put("وحدة","Business Affairs / Pricing or Billing");
        dictionary.put("تسرقوا","Business Affairs / Pricing or Billing");
        dictionary.put("بتنصبوا","Business Affairs / Pricing or Billing");
        dictionary.put("الفواتير","Business Affairs / Pricing or Billing");
        dictionary.put("الفلوس","Business Affairs / Pricing or Billing");
        dictionary.put("الضرايب","Business Affairs / Pricing or Billing");
        dictionary.put("السرقه","Business Affairs / Pricing or Billing");
        dictionary.put("التسعيرات","Business Affairs / Pricing or Billing");
        dictionary.put("الايصال","Business Affairs / Pricing or Billing");
        dictionary.put("الاسعار","Business Affairs / Pricing or Billing");
        dictionary.put("نصبوا","Business Affairs / Pricing or Billing");
        dictionary.put("نصبتوا","Business Affairs / Pricing or Billing");
        dictionary.put("نصبت","Business Affairs / Pricing or Billing");
        dictionary.put("نصابيين","Business Affairs / Pricing or Billing");
        dictionary.put("نصابين","Business Affairs / Pricing or Billing");
        dictionary.put("نصابه","Business Affairs / Pricing or Billing");
        dictionary.put("نصابة","Business Affairs / Pricing or Billing");
        dictionary.put("نصاب","Business Affairs / Pricing or Billing");
        dictionary.put("مليم","Business Affairs / Pricing or Billing");
        dictionary.put("مصاريف","Business Affairs / Pricing or Billing");
        dictionary.put("مشحنش","Business Affairs / Pricing or Billing");
        dictionary.put("مشحن","Business Affairs / Pricing or Billing");
        dictionary.put("للنصب","Business Affairs / Pricing or Billing");
        dictionary.put("للفاتورة","Business Affairs / Pricing or Billing");
        dictionary.put("لفلوس","Business Affairs / Pricing or Billing");
        dictionary.put("لفاتوره","Business Affairs / Pricing or Billing");
        dictionary.put("لصوص","Business Affairs / Pricing or Billing");
        dictionary.put("لرصيدك","Business Affairs / Pricing or Billing");
        dictionary.put("كريديت","Business Affairs / Pricing or Billing");
        dictionary.put("كريدت","Business Affairs / Pricing or Billing");
        dictionary.put("كروت","Business Affairs / Pricing or Billing");
        dictionary.put("كرتين","Business Affairs / Pricing or Billing");
        dictionary.put("كرت","Business Affairs / Pricing or Billing");
        dictionary.put("كاش","Business Affairs / Pricing or Billing");
        dictionary.put("الكريدت كارد","Business Affairs / Pricing or Billing");
        dictionary.put("بالكريدت كارد","Business Affairs / Pricing or Billing");
        dictionary.put("بالماستر كارد","Business Affairs / Pricing or Billing");
        dictionary.put("كريدت كارد","Business Affairs / Pricing or Billing");
        dictionary.put("كارتين","Business Affairs / Pricing or Billing");
        dictionary.put("كارت","Business Affairs / Pricing or Billing");
        dictionary.put("فواتير","Business Affairs / Pricing or Billing");
        dictionary.put("فلوووسي","Business Affairs / Pricing or Billing");
        dictionary.put("فلووس","Business Affairs / Pricing or Billing");
        dictionary.put("فلوسي","Business Affairs / Pricing or Billing");
        dictionary.put("فلوسها","Business Affairs / Pricing or Billing");
        dictionary.put("فلوسك","Business Affairs / Pricing or Billing");
        dictionary.put("فالرصيد","Business Affairs / Pricing or Billing");
        dictionary.put("فاشحنت","Business Affairs / Pricing or Billing");
        dictionary.put("فاتوره","Business Affairs / Pricing or Billing");
        dictionary.put("فاتورتي","Business Affairs / Pricing or Billing");
        dictionary.put("فاتورتى","Business Affairs / Pricing or Billing");
        dictionary.put("فاتورة","Business Affairs / Pricing or Billing");
        dictionary.put("شحن","Business Affairs / Pricing or Billing");
        dictionary.put("رصيد","Business Affairs / Pricing or Billing");
        dictionary.put("دفعتها","Business Affairs / Pricing or Billing");
        dictionary.put("دفع","Business Affairs / Pricing or Billing");
        dictionary.put("جنية","Business Affairs / Pricing or Billing");
        dictionary.put("بينصبوا","Business Affairs / Pricing or Billing");
        dictionary.put("بينصب","Business Affairs / Pricing or Billing");
        dictionary.put("بنصب","Business Affairs / Pricing or Billing");
        dictionary.put("بنتسرق","Business Affairs / Pricing or Billing");
        dictionary.put("بمبلغ","Business Affairs / Pricing or Billing");
        dictionary.put("برصيد","Business Affairs / Pricing or Billing");
        dictionary.put("بتنصبو","Business Affairs / Pricing or Billing");
        dictionary.put("بتسرقونا","Business Affairs / Pricing or Billing");
        dictionary.put("بتتسرق","Business Affairs / Pricing or Billing");
        dictionary.put("الكريديت","Business Affairs / Pricing or Billing");
        dictionary.put("الفاتوره","Business Affairs / Pricing or Billing");
        dictionary.put("الدفع","Business Affairs / Pricing or Billing");
        dictionary.put("اتنصب","Business Affairs / Pricing or Billing");
        dictionary.put("recharge","Business Affairs / Pricing or Billing");
        dictionary.put("rasid","Business Affairs / Pricing or Billing");
        dictionary.put("raseed","Business Affairs / Pricing or Billing");
        dictionary.put("الكود","Business Affairs / Other Business Affairs");
        dictionary.put("الرقم","Business Affairs / Other Business Affairs");
        dictionary.put("فيروس","Business Affairs / Other Business Affairs");
        dictionary.put("التكنيكالز","Business Affairs / Other Business Affairs");
        dictionary.put("التكنيكال","Business Affairs / Other Business Affairs");
        dictionary.put("الابليكيشن","Business Affairs / Other Business Affairs");
        dictionary.put("الابليكشن","Business Affairs / Other Business Affairs");
        dictionary.put("عقد","Business Affairs / Contracts");
        dictionary.put("العروض","Business Affairs / Products and Plans");
        dictionary.put("خدمة","Business Affairs / Products and Plans");
        dictionary.put("خدمات","Business Affairs / Products and Plans");
        dictionary.put("باقة","Business Affairs / Products and Plans");
        dictionary.put("العرض","Business Affairs / Products and Plans");
        dictionary.put("الخدمه","Business Affairs / Products and Plans");
        dictionary.put("الخدمات","Business Affairs / Products and Plans");
        dictionary.put("الباقة","Business Affairs / Products and Plans");
        dictionary.put("لخدمه","Business Affairs / Products and Plans");
        dictionary.put("لخدمت","Business Affairs / Products and Plans");
        dictionary.put("لخدمة","Business Affairs / Products and Plans");
        dictionary.put("الباندل","Business Affairs / Products and Plans");
        dictionary.put("الباقات","Business Affairs / Products and Plans");
        dictionary.put("راوتر","Network / Data");
        dictionary.put("msg","Network / Messaging");
        dictionary.put("message","Network / Messaging");
        dictionary.put("الرساله","Network / Messaging");
        dictionary.put("Note 2","Business Affairs / Handset");
        dictionary.put("القرش","Business Affairs / Pricing or Billing");
        dictionary.put("لضريبه","Business Affairs / Pricing or Billing");
        dictionary.put("بفلوس","Business Affairs / Pricing or Billing");
        dictionary.put("الأسعار","Business Affairs / Pricing or Billing");
        dictionary.put("باقه","Business Affairs / Products and Plans");
        dictionary.put("الفيلكس","Business Affairs / Products and Plans");
        dictionary.put("فيلكس","Business Affairs / Products and Plans");
        dictionary.put("فليكس","Business Affairs / Products and Plans");
        dictionary.put("كنترول","Business Affairs / Products and Plans");
        dictionary.put("عرض","Business Affairs / Products and Plans");	
        dictionary.put("فلكس","Business Affairs / Products and Plans");
        dictionary.put("رسايل","Network / Messaging");
        dictionary.put("sms","Network / Messaging");
        dictionary.put("المسج","Network / Messaging");
        dictionary.put("nasb","Business Affairs / Pricing or Billing");
        dictionary.put("invoice","Business Affairs / Pricing or Billing");
        dictionary.put("الحرامية","Business Affairs / Pricing or Billing");
        dictionary.put("اسرقوا","Business Affairs / Pricing or Billing");
        dictionary.put("بتنصب","Business Affairs / Pricing or Billing");
        dictionary.put("e-payment","Business Affairs / Pricing or Billing");
        dictionary.put("payment","Business Affairs / Pricing or Billing");
        dictionary.put("prepaid","Business Affairs / Pricing or Billing");
        dictionary.put("rate","Business Affairs / Pricing or Billing");
        dictionary.put("اسعارها","Business Affairs / Pricing or Billing");
        dictionary.put("الفيس","Business Affairs / Other Business Affairs");
        dictionary.put("فيس","Business Affairs / Other Business Affairs");
        dictionary.put("الفاسبوك","Business Affairs / Other Business Affairs");
        dictionary.put("الفايسبوك","Business Affairs / Other Business Affairs");
        dictionary.put("فاسبوك","Business Affairs / Other Business Affairs");
        dictionary.put("فايسبوك","Business Affairs / Other Business Affairs");
        dictionary.put("انستا","Business Affairs / Other Business Affairs");
        dictionary.put("فيبير","Business Affairs / Other Business Affairs");
        dictionary.put("فايبر","Business Affairs / Other Business Affairs");
        dictionary.put("واتس","Business Affairs / Other Business Affairs");
        dictionary.put("وتسب","Business Affairs / Other Business Affairs");
        dictionary.put("واتساب","Business Affairs / Other Business Affairs");
        dictionary.put("ايزي","Business Affairs / Products and Plans");
        dictionary.put("الخدمة","Business Affairs / Products and Plans");
        dictionary.put("bundle","Business Affairs / Products and Plans");
        dictionary.put("الپاكيدچ","Business Affairs / Products and Plans");
        dictionary.put("باقتين","Business Affairs / Products and Plans");
	}
	
    

    public Text evaluate(final Text s)
    {  
    	float sim=0;
        String result="";
    	String type;
    	String[] words;
      initDictionary();
      if (s == null)
      { return null; }  
        words = s.toString().trim().split("\\s+");
		for (int i = 0; i < words.length; i++) {
			words[i]=words[i].trim().replace(" ", "");
      for(String key: dictionary.keySet())
	    {
      sim=getSimilarity (key.toLowerCase(),words[i].toString().toLowerCase());
		if (sim >= 0.7)
		{
			type=dictionary.get(key);
			if (result.length() ==0)
			  result = type;
	       else if (!result.contains(type))
            	result = result + " | " + type;}
			
		}
		}
		
	      if (result.equals(""))
	    	  return new Text("Business Affairs / Other Business Affairs");
	    	else 
      return new Text(result);       
     }  
   
		public static float getSimilarity(String str1,String str2)
	    {
//	            AbstractStringMetric metric = new Levenshtein();
//	            AbstractStringMetric metric = new CosineSimilarity();
//	            AbstractStringMetric metric = new EuclideanDistance();
//	            AbstractStringMetric metric = new MongeElkan();
	            AbstractStringMetric metricL = new Levenshtein();
	            AbstractStringMetric metricM = new MongeElkan();

	            float resultL = metricL.getSimilarity(str1, str2);
	            float resultM = metricM.getSimilarity(str1, str2);
	            float result;
	            if (str2.length() > 3)
                result = (resultL + resultM) / 2;
	            // to compare to 0.75 instead of 0.7
	            else result = (float) (resultL-0.05);

	            return result;
	    	
	    }	
}
