msck repair table youtube_ChannelFeed;
msck repair table youtube_ChronologicalChannelKpis;
msck repair table youtube_Search;
msck repair table youtube_Subscribers;
msck repair table youtube_Subscriptions;
msck repair table youtube_TopVideos;
msck repair table youtube_VideoComments;
msck repair table youtube_VideoList;
msck repair table youtube_VideoStatistics;